name: pepetly
services:
  pepetly:
    container_name: pepetly
    image: nginx:alpine
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - .env

    networks:
      - pepet-network

networks:
  pepet-network:
    external: true
