name: pepetly
services:
  pepetly:
    container_name: pepetly
    image: nginx:alpine
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html:ro
    env_file:
      - .env

    networks:
      - pepet-network

networks:
  pepet-network:
    external: true
